# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eurokambiyous.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(250, 306)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(250, 306))
        MainWindow.setMaximumSize(QtCore.QSize(250, 306))
        MainWindow.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 251, 51))
        self.label.setStyleSheet("background-color: rgb(95, 74, 255);\n"
"font: 20pt \"Onyx\";")
        self.label.setObjectName("label")
        self.euro_metin = QtWidgets.QLabel(self.centralwidget)
        self.euro_metin.setGeometry(QtCore.QRect(0, 70, 151, 41))
        self.euro_metin.setStyleSheet("font: 16pt \"Niagara Solid\";\n"
"background-color: rgb(85, 85, 255);\n"
"color: rgb(0, 0, 0);")
        self.euro_metin.setObjectName("euro_metin")
        self.euro_deger = QtWidgets.QLineEdit(self.centralwidget)
        self.euro_deger.setGeometry(QtCore.QRect(150, 70, 101, 41))
        self.euro_deger.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Rockwell Condensed\";")
        self.euro_deger.setText("")
        self.euro_deger.setObjectName("euro_deger")
        self.parabirimi = QtWidgets.QComboBox(self.centralwidget)
        self.parabirimi.setGeometry(QtCore.QRect(0, 140, 251, 22))
        self.parabirimi.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.parabirimi.setObjectName("parabirimi")
        self.parabirimi.addItem("")
        self.parabirimi.addItem("")
        self.parabirimi.addItem("")
        self.parabirimi.addItem("")
        self.parabirimi.addItem("")
        self.parabirimi.addItem("")
        self.parabirimi.addItem("")
        self.parabirimi.addItem("")
        self.parabirimi.addItem("")
        self.parabirimi.addItem("")
        self.parabirimi.addItem("")
        self.cevir_button = QtWidgets.QPushButton(self.centralwidget)
        self.cevir_button.setGeometry(QtCore.QRect(0, 170, 171, 61))
        self.cevir_button.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.cevir_button.setObjectName("cevir_button")
        self.sonuc = QtWidgets.QLabel(self.centralwidget)
        self.sonuc.setGeometry(QtCore.QRect(0, 230, 251, 41))
        self.sonuc.setStyleSheet("background: transparent;")
        self.sonuc.setText("")
        self.sonuc.setObjectName("sonuc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "              EURO KAMBİYOSU"))
        self.euro_metin.setText(_translate("MainWindow", "BOZULACAK EURO MİKTARI:"))
        self.parabirimi.setItemText(0, _translate("MainWindow", "Lütfen çevrilecek Para birimi seçiniz"))
        self.parabirimi.setItemText(1, _translate("MainWindow", "Amerikan Doları (USD)"))
        self.parabirimi.setItemText(2, _translate("MainWindow", "İngiliz Sterlini(GBP)"))
        self.parabirimi.setItemText(3, _translate("MainWindow", "Renbinmi (CNY)-YEN"))
        self.parabirimi.setItemText(4, _translate("MainWindow", "Hindistan Rupisi(INR)"))
        self.parabirimi.setItemText(5, _translate("MainWindow", "BEA Dirhemi (AED)"))
        self.parabirimi.setItemText(6, _translate("MainWindow", "Japon Yeni (JPY)"))
        self.parabirimi.setItemText(7, _translate("MainWindow", "İsviçre Frangı (CHF)"))
        self.parabirimi.setItemText(8, _translate("MainWindow", "Güney Kore Wonu(KRW)"))
        self.parabirimi.setItemText(9, _translate("MainWindow", "Güney Afrika (ZAR)"))
        self.parabirimi.setItemText(10, _translate("MainWindow", "Türk Lirası (TRY)"))
        self.cevir_button.setText(_translate("MainWindow", "ÇEVİR"))
